import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { getFeaturedImages, getVideos } from "@/lib/content-db";
import { VideoGallery } from "@/components/VideoGallery";
import { packages } from "@/content/packages";
import { locations } from "@/content/locations";

export const revalidate = 60;
export const metadata: Metadata = {
  title: "Fotografía y Video de Quinceañeras en Dallas–Fort Worth",
  description: "Fotos y video de quinceañera en Dallas–Fort Worth. Celebraciones reales, precios claros desde $1,800 y una respuesta personal en 24 horas.",
  alternates: { canonical: "/es", languages: { "en-US": "/", "es-MX": "/es" } },
  openGraph: { locale: "es_MX" },
};

export default async function InicioEs() {
  const [images, videos] = await Promise.all([getFeaturedImages(12), getVideos()]);
  const hero = images[0];
  return <>
    <section className="grid border-b border-line bg-white lg:grid-cols-12"><div className="flex flex-col justify-center px-5 py-20 md:px-10 md:py-28 lg:col-span-7 lg:px-16"><p className="text-xs font-medium uppercase tracking-[0.2em] text-wine-deep">Fotografía y video de quinceañeras · Dallas–Fort Worth</p><h1 className="mt-6 max-w-[11ch] font-serif text-[clamp(3.6rem,7vw,7rem)] leading-[0.92] tracking-[-0.045em] text-ink">Su historia merece sentirse como ella.</h1><p className="mt-7 max-w-[50ch] text-lg leading-8 text-ink-soft">La misa, el vals, las miradas de la familia y cada detalle que ella eligió. Foto y video de quinceañeras con una mirada personal, en todo Dallas–Fort Worth.</p><div className="mt-9 flex flex-wrap items-center gap-5"><Link href="/es/consulta" className="inline-flex min-h-12 items-center rounded-full bg-ink px-7 text-sm font-semibold text-white hover:bg-ink/85">Consulta su fecha →</Link><Link href="/es/paquetes" className="text-sm font-medium text-ink underline underline-offset-4">Ver paquetes</Link></div><p className="mt-4 text-sm text-ink-soft">Consultar disponibilidad es gratis · Respuesta personal en 24 horas</p></div><div className="relative min-h-[400px] lg:col-span-5 lg:min-h-[700px] bg-greige">{hero?.url ? <Image src={hero.url} alt={hero.alt || "Quinceañera en Dallas–Fort Worth"} fill priority sizes="(max-width: 1024px) 100vw, 42vw" className="object-cover" /> : null}</div></section>
    <section className="mx-auto max-w-[90rem] px-5 py-20 md:px-10 md:py-28 lg:px-16"><div className="grid gap-8 md:grid-cols-12"><div className="md:col-span-5"><p className="text-xs font-medium uppercase tracking-[0.2em] text-wine-deep">Celebraciones reales</p><h2 className="mt-4 font-serif text-[clamp(2.7rem,5vw,4.7rem)] leading-none text-ink">Mira lo que recordarán.</h2></div><p className="max-w-md self-end text-base leading-7 text-ink-soft md:col-span-5 md:col-start-8">Familias reales, salones reales y una historia diferente en cada quinceañera. Conoce el trabajo antes de reservar.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{images.slice(1, 7).map((img) => <div key={img.id} className="relative aspect-[4/5] bg-greige"><Image src={img.url} alt={img.alt || "Retrato de quinceañera"} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover" /></div>)}</div><Link href="/portfolio" className="mt-8 inline-flex text-sm font-semibold text-ink underline underline-offset-4">Ver el portafolio →</Link></section>
    {videos.length > 0 ? <section className="border-y border-line bg-white"><div className="mx-auto max-w-[90rem] px-5 py-20 md:px-10 md:py-28 lg:px-16"><h2 className="font-serif text-[clamp(2.7rem,5vw,4.5rem)] leading-none text-ink">El día también se escucha.</h2><p className="mb-9 mt-4 text-base leading-7 text-ink-soft">La música, las palabras y las risas que una foto no puede guardar.</p><VideoGallery videos={videos.filter((v) => v.orientation !== "vertical").slice(0, 3)} /><Link href="/es/videografo-de-quinceaneras" className="mt-8 inline-flex text-sm font-semibold text-ink underline underline-offset-4">Ver los videos →</Link></div></section> : null}
    <section className="bg-greige"><div className="mx-auto max-w-[90rem] px-5 py-20 md:px-10 md:py-28 lg:px-16"><p className="text-xs font-medium uppercase tracking-[0.2em] text-wine-deep">Colecciones sin sorpresas</p><h2 className="mt-4 font-serif text-[clamp(2.7rem,5vw,4.5rem)] leading-none text-ink">Una forma de recordarla, a tu medida.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{packages.map((p) => <Link key={p.id} href="/es/paquetes" className="group border border-line bg-white p-6 hover:border-ink"><h3 className="font-serif text-3xl text-ink">{p.name}</h3><p className="mt-6 font-serif text-4xl text-ink">{p.priceLabel}</p><p className="mt-2 text-sm text-ink-soft">Depósito: {p.depositLabel}</p><span className="mt-6 inline-block text-sm text-ink underline underline-offset-4">Ver detalles →</span></Link>)}</div><Link href="/es/planes-de-pago" className="mt-8 inline-flex text-sm font-semibold text-ink underline underline-offset-4">Conoce los planes de pago →</Link></div></section>
    <section className="mx-auto max-w-[90rem] px-5 py-20 md:px-10 md:py-28 lg:px-16"><h2 className="font-serif text-[clamp(2.7rem,5vw,4.5rem)] leading-none text-ink">En todo Dallas–Fort Worth.</h2><p className="mt-4 max-w-xl text-base leading-7 text-ink-soft">De la iglesia al salón, acompañamos a familias en toda la región.</p><div className="mt-9 flex flex-wrap gap-3">{locations.map((l) => <Link key={l.slug} href={`/es/fotografo-de-quinceaneras/${l.slug}`} className="rounded-full border border-line px-5 py-3 text-sm text-ink hover:border-ink">{l.city}</Link>)}</div><Link href="/es/salones" className="mt-8 inline-flex text-sm font-semibold text-ink underline underline-offset-4">Explora los salones →</Link></section>
    <section className="bg-ink"><div className="mx-auto max-w-[90rem] px-5 py-20 md:px-10 md:py-28 lg:px-16"><p className="text-xs uppercase tracking-[0.2em] text-white/60">Solo una celebración por día</p><h2 className="mt-5 max-w-[12ch] font-serif text-[clamp(3rem,6vw,5.5rem)] leading-[0.95] text-white">¿Está libre su fecha?</h2><Link href="/es/consulta" className="mt-9 inline-flex min-h-12 items-center rounded-full bg-white px-7 text-sm font-semibold text-ink">Consulta su fecha →</Link></div></section>
  </>;
}
