import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { getFeaturedImages, getVideos } from "@/lib/content-db";
import { VideoGallery } from "@/components/VideoGallery";
import { packages } from "@/content/packages";
import { locations } from "@/content/locations";
import { portfolioFallback } from "@/content/portfolio-fallback";

export const revalidate = 60;
export const metadata: Metadata = {
  title: "Fotografía y Video de Quinceañeras en Dallas–Fort Worth",
  description: "Fotos y video de quinceañera en Dallas–Fort Worth. Celebraciones reales, precios claros desde $1,800 y una respuesta personal en 24 horas.",
  alternates: { canonical: "/es", languages: { "en-US": "/", "es-MX": "/es" } },
  openGraph: { locale: "es_MX" },
};

export default async function InicioEs() {
  const [images, videos] = await Promise.all([getFeaturedImages(12), getVideos()]);
  const displayImages = images.length ? images : portfolioFallback.filter((image) => image.slug !== "domed-ballroom-portrait");
  const hero = displayImages[0];
  return <>
    <section className="border-b border-line bg-white"><div className="mx-auto flex max-w-3xl flex-col items-center px-5 pb-12 pt-14 text-center md:px-10 md:pb-16 md:pt-20"><p className="text-xs font-medium uppercase tracking-[0.2em] text-ink-soft">Fotografía y video de quinceañeras · Dallas–Fort Worth</p><h1 className="mt-5 max-w-[22ch] font-display text-[clamp(2rem,3.4vw,3rem)] leading-[1.15] tracking-[-0.03em] text-ink">Su historia merece sentirse como ella.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-ink-soft">La misa, el vals, las miradas de la familia y cada detalle que ella eligió. Foto y video de quinceañeras con una mirada personal, en todo Dallas–Fort Worth.</p><div className="mt-7 flex flex-wrap items-center justify-center gap-4"><Link href="/es/consulta" className="inline-flex min-h-12 items-center whitespace-nowrap rounded-lg bg-ink px-6 text-base font-medium text-white hover:bg-accent-strong focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ink">Consulta su fecha →</Link><Link href="/es/paquetes" className="inline-flex min-h-11 items-center text-base font-medium text-ink underline underline-offset-4">Ver paquetes</Link></div><p className="mt-4 text-base text-ink-soft">Consultar disponibilidad es gratis · Respuesta personal en 24 horas</p></div><div className="relative mx-5 aspect-[4/3] overflow-hidden rounded-lg bg-greige sm:aspect-[16/8] md:mx-10 lg:mx-16">{hero?.url ? <Image src={hero.url} alt={hero.alt || "Quinceañera en Dallas–Fort Worth"} fill priority sizes="100vw" className="object-cover" style={!images.length ? { objectPosition: "center 70%" } : undefined} /> : null}</div></section>
    <section className="mx-auto max-w-[90rem] px-5 py-16 md:px-10 md:py-20 lg:px-16"><div className="grid gap-8 md:grid-cols-12"><div className="md:col-span-5"><p className="text-xs font-medium uppercase tracking-[0.2em] text-ink-soft">Celebraciones reales</p><h2 className="mt-4 font-display text-[clamp(1.75rem,2.8vw,2.5rem)] leading-tight text-ink">Mira lo que recordarán.</h2></div><p className="max-w-md self-end text-base leading-7 text-ink-soft md:col-span-5 md:col-start-8">Familias reales, salones reales y una historia diferente en cada quinceañera. Conoce el trabajo antes de reservar.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{displayImages.slice(1, 7).map((img) => <div key={img.url} className="relative aspect-[4/5] overflow-hidden rounded-lg bg-greige"><Image src={img.url} alt={img.alt || "Retrato de quinceañera"} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover" /></div>)}</div><Link href="/portfolio" className="mt-8 inline-flex min-h-11 items-center text-base font-medium text-ink underline underline-offset-4">Ver el portafolio →</Link></section>
    {videos.length > 0 ? <section className="border-y border-line bg-white"><div className="mx-auto max-w-[90rem] px-5 py-16 md:px-10 md:py-20 lg:px-16"><h2 className="font-display text-[clamp(1.75rem,2.8vw,2.5rem)] leading-tight text-ink">El día también se escucha.</h2><p className="mb-9 mt-4 text-base leading-7 text-ink-soft">La música, las palabras y las risas que una foto no puede guardar.</p><VideoGallery videos={videos.filter((v) => v.orientation !== "vertical").slice(0, 3)} /><Link href="/es/videografo-de-quinceaneras" className="mt-8 inline-flex min-h-11 items-center text-base font-medium text-ink underline underline-offset-4">Ver los videos →</Link></div></section> : null}
    <section className="bg-white"><div className="mx-auto max-w-[90rem] px-5 py-16 md:px-10 md:py-20 lg:px-16"><p className="text-xs font-medium uppercase tracking-[0.2em] text-ink-soft">Colecciones sin sorpresas</p><h2 className="mt-4 font-display text-[clamp(1.75rem,2.8vw,2.5rem)] leading-tight text-ink">Una forma de recordarla, a tu medida.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{packages.map((p) => <Link key={p.id} href="/es/paquetes" className="group flex min-h-52 flex-col rounded-lg border border-line bg-white p-6 hover:border-ink focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ink"><h3 className="font-display text-[1.5rem] text-ink">{p.name}</h3><p className="mt-6 font-display text-[1.75rem] text-ink">{p.priceLabel}</p><p className="mt-2 text-base text-ink-soft">Depósito: {p.depositLabel}</p><span className="mt-auto inline-flex min-h-11 items-center text-base text-ink underline underline-offset-4">Ver detalles →</span></Link>)}</div><Link href="/es/planes-de-pago" className="mt-8 inline-flex min-h-11 items-center text-base font-medium text-ink underline underline-offset-4">Conoce los planes de pago →</Link></div></section>
    <section className="mx-auto max-w-[90rem] px-5 py-16 md:px-10 md:py-20 lg:px-16"><h2 className="font-display text-[clamp(1.75rem,2.8vw,2.5rem)] leading-tight text-ink">En todo Dallas–Fort Worth.</h2><p className="mt-4 max-w-xl text-base leading-7 text-ink-soft">De la iglesia al salón, acompañamos a familias en toda la región.</p><div className="mt-9 flex flex-wrap gap-3">{locations.map((l) => <Link key={l.slug} href={`/es/fotografo-de-quinceaneras/${l.slug}`} className="inline-flex min-h-11 items-center rounded-lg border border-line px-5 text-base text-ink hover:border-ink">{l.city}</Link>)}</div><Link href="/es/salones" className="mt-8 inline-flex min-h-11 items-center text-base font-medium text-ink underline underline-offset-4">Explora los salones →</Link></section>
    <section className="bg-accent-soft"><div className="mx-auto max-w-[90rem] px-5 py-16 md:px-10 md:py-20 lg:px-16"><p className="text-xs uppercase tracking-[0.16em] text-ink-soft">Solo una celebración por día</p><h2 className="mt-5 font-display text-[clamp(1.75rem,2.8vw,2.5rem)] leading-tight text-ink">¿Está libre su fecha?</h2><Link href="/es/consulta" className="mt-7 inline-flex min-h-12 items-center whitespace-nowrap rounded-lg bg-ink px-6 text-base font-medium text-white hover:bg-accent-strong focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ink">Consulta su fecha →</Link></div></section>
  </>;
}
